<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.core.NestedExceptionTests" tests="4" skipped="0" failures="0" errors="0" timestamp="2019-08-24T10:31:40" hostname="XULANLAN" time="0.015">
  <properties/>
  <testcase name="nestedRuntimeExceptionWithRootCause" classname="org.springframework.core.NestedExceptionTests" time="0.005"/>
  <testcase name="nestedCheckedExceptionWithRootCause" classname="org.springframework.core.NestedExceptionTests" time="0.002"/>
  <testcase name="nestedRuntimeExceptionWithNoRootCause" classname="org.springframework.core.NestedExceptionTests" time="0.004"/>
  <testcase name="nestedCheckedExceptionWithNoRootCause" classname="org.springframework.core.NestedExceptionTests" time="0.002"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
